[package]
name = "polkit"
version = "127"
description = "uhh just polkit nothing special"
source = "https://github.com/polkit-org/polkit/archive/127/polkit-127.tar.gz"

[build]
system = "manual"
build_commands = "mkdir build && meson setup build --prefix=/usr --buildtype=release -D os_type=lfs -D man=false -D session_tracking=elogind -D systemdsystemunitdir=/tmp -D tests=false && ninja -C build -j$RAD_CORES"
install_command = "ninja install -C build"
depends = "duktape"
