[package]
name = "fish"
version = "git"
description = "fish is a smart and user-friendly command line shell for macOS, Linux, and the rest of the family"
source = "https://github.com/fish-shell/fish-shell.git"

[build]
system = "manual"
build_commands = "cargo build --release"
install_command = "mkdir $DESTDIR/bin -p && cp ./target/release/fish $DESTDIR/bin/fish"
dependencies = "coreutils"
