[package]
name = "coreutils"
version = "9.10"
description = "The Coreutils package contains the basic utility programs needed by every operating system"
source = "https://ftpmirror.gnu.org/coreutils/coreutils-9.10.tar.xz"

[build]
system = "manual"
multilib_support = "false"
build_commands = "wget https://www.linuxfromscratch.org/patches/lfs/13.0/coreutils-9.10-i18n-1.patch && patch -Np1 -i ./coreutils-9.10-i18n-1.patch && autoreconf -fv && automake -af && FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr && make"
install_command = "make install && mkdir $DESTDIR/usr/sbin && mv -v $DESTDIR/usr/bin/chroot $DESTDIR/usr/sbin/ && mkdir $DESTDIR/usr/share/man/man8 -p && mv -v $DESTDIR/usr/share/man/man1/chroot.1 $DESTDIR/usr/share/man/man8/chroot.8 && sed -i 's/"1"/"8"/' $DESTDIR/usr/share/man/man8/chroot.8"
