[package]
name = "dinit"
version = "0.21.0"
description = "Dinit is a service manager or supervision system, which can also function as a system manager and init"
source = "https://github.com/davmac314/dinit/archive/refs/tags/v0.21.0.tar.gz"

[build]
system = "autotools"
