[package]
name = "npth"
version = "1.8"
description = "The NPth package contains a very portable POSIX/ANSI-C based library for Unix platforms which provides non-preemptive priority-based scheduling for multiple threads of execution (multithreading) inside event-driven applications"
source = "https://www.gnupg.org/ftp/gcrypt/npth/npth-1.8.tar.bz2"

[build]
system = "autotools"
