[package]
name = "rad"
version = "git"
description = "rad is a source-based package manager for Radrix GNU/Linux or other GNU/Linux distros"
source = "https://github.com/dejuri/rad.git"

[build]
system = "cargo"
