[package]
name = "imagemagick"
version = "7.1.2-13"
description = "ImageMagick® is a free, open-source software suite, used for editing and manipulating digital images"
source = "https://www.imagemagick.org/archive/releases/ImageMagick-7.1.2-13.tar.xz"

[build]
system = "manual"
build_commands = "./configure --prefix=/usr --sysconfdir=/etc --enable-hdri --with-modules --with-perl --disable-static && make -j$RAD_CORES"
install_command = "make DOCUMENTATION_PATH=/usr/share/doc/imagemagick-7.1.2 install"
depends = ""
configure_args = ""
