[package]
name = "xdg-utils"
version = "1.2.1"
description = "xdg-utils is a set of command line tools that assist applications with a variety of desktop integration tasks"
source = "https://gitlab.freedesktop.org/xdg/xdg-utils/-/archive/v1.2.1/xdg-utils-v1.2.1.tar.gz"

[build]
system = "autotools"
depends = "xmlto,links"
