[package]
name = "libbpf"
version = "1.7.0"
description = "Stand-alone build of libbpf from the Linux kernel"
source = "https://github.com/libbpf/libbpf/archive/refs/tags/v1.7.0.tar.gz"

[build]
system = "manual"
build_commands = "make -C src -j$RAD_CORES"
install_command = "make DESTDIR=$DESTDIR -C src install"
