[package]
name = "ffmpeg"
version = "8.1"
description = "FFmpeg is a solution to record, convert and stream audio and video and bla bla bla and it is very fast btw"
source = "https://ffmpeg.org/releases/ffmpeg-8.1.tar.xz"

[build]
system = "manual"
build_commands = "wget https://www.linuxfromscratch.org/patches/blfs/svn/ffmpeg-8.1-chromium_method-1.patch && patch -Np1 -i ./ffmpeg-8.1-chromium_method-1.patch && ./configure --prefix=/usr --enable-gpl --enable-version3 --enable-nonfree --disable-static --enable-shared --disable-debug --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-openssl --enable-libdav1d --enable-libsvtav1 --ignore-tests=enhanced-flv-av1,enhanced-flv-multitrack --docdir=/usr/share/doc/ffmpeg-8.1 && make && gcc tools/qt-faststart.c -o tools/qt-faststart"
install_command = "make install"
depends = "fribidi,libass,freetype,dav1d,libaom,fdk-aac,lame,svt-av1,libvpx,opus,x264,x265,sdl2-compat,nasm"
