[package]
name = "gcc"
version = "15.2.0"
description = "The GCC package contains the GNU compiler collection, which includes the C and C++ compilers"
source = "https://ftpmirror.gnu.org/gcc/gcc-15.2.0/gcc-15.2.0.tar.xz"

[build]
system = "manual"
build_commands = "wget https://raw.githubusercontent.com/dejuri/radpkg/main/stable-13/gcc.sh && bash -e ./gcc.sh build"
install_command = "bash -e ./gcc.sh install"
depends = "zlib"
