[package]
name = "glslc"
version = "2025.3"
description = "The glslc program is Google's command line compiler for OpenGL Shading Language/High Level Shading Language (GLSL/HLSL) to Standard Portable Intermediate Representation (SPIR-V)"
source = "https://github.com/google/shaderc/archive/v2025.3/shaderc-2025.3.tar.gz"

[build]
system = "manual"
build_commands = "sed '/build-version/d' -i glslc/CMakeLists.txt && sed '/third_party/d' -i CMakeLists.txt && sed 's|SPIRV|glslang/&|' -i libshaderc_util/src/compiler.cc && echo '"2025.3"' > glslc/src/build-version.inc && mkdir build && cmake -B build -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D SHADERC_SKIP_TESTS=ON -G Ninja && ninja -C build"
install_command = "mkdir $DESTDIR/usr/bin -p && install -vm755 build/glslc/glslc $DESTDIR/usr/bin"
