[package]
name = "libadwaita"
version = "1.9.0"
description = "The libadwaita package provides additional GTK4 UI widgets for use in developing user interfaces. It is used primarily for GNOME applications"
source = "https://download.gnome.org/sources/libadwaita/1.9/libadwaita-1.9.0.tar.xz"

[build]
system = "meson"
configure_args = "--buildtype=release -D examples=false -D tests=false -D introspection=disabled -D appstream:bash-completion=false -D appstream:apidocs=false -D appstream:man=false -D appstream:gir=false"
depends = "appstream,gtk4,sassc"
