[package]
name = "nasm"
version = "3.01"
source = "https://www.nasm.us/pub/nasm/releasebuilds/3.01/nasm-3.01.tar.xz"
description = "NASM (Netwide Assembler) is an 80x86 assembler designed for portability and modularity. It includes a disassembler as well"

[build]
system = "autotools"
