[package]
name = "test"
source = "https://raw.githubusercontent.com/Syripagan/raph-pkgs/main/test.raph"

[build]
system = "manual"
build_commands = "echo 'i wanted to build something, test is nice btw'"
install_command = "echo 'ok look test completed succesfully'"
depends = ""
configure_args = ""
