[package]
name = "docbook-xsl-nons"
version = "1.79.2"
description = "The DocBook XSL Stylesheets package contains XSL stylesheets"
source = "https://github.com/docbook/xslt10-stylesheets/releases/download/release/1.79.2/docbook-xsl-nons-1.79.2.tar.bz2"

[build]
system = "manual"
build_commands = [
	"wget https://www.linuxfromscratch.org/patches/blfs/svn/docbook-xsl-nons-1.79.2-stack_fix-1.patch",
	"patch -Np1 -i ./docbook-xsl-nons-1.79.2-stack_fix-1.patch",
]
install_command = [
	"install -v -m755 -d $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2",
	"cp -v -R VERSION assembly common eclipse epub epub3 extensions fo highlighting html htmlhelp images javahelp lib manpages params profiling roundtrip slides template tests tools webhelp website xhtml xhtml-1_1 xhtml5 $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2",
	"ln -svf VERSION $DESTDIR/usr/share/xml/docbook/xsl-stylesheets-nons-1.79.2/VERSION.xsl",
	"install -v -m644 -D README $DESTDIR/usr/share/doc/docbook-xsl-nons-1.79.2/README.txt",
	"install -v -m644 RELEASE-NOTES* NEWS* $DESTDIR/usr/share/doc/docbook-xsl-nons-1.79.2"
]
depends = "libxml2"
