[package]
name = "xmlto"
version = "0.0.29"
description = "The xmlto package is a front-end to a XSL toolchain"
source = "https://pagure.io/xmlto/archive/0.0.29/xmlto-0.0.29.tar.gz"

[build]
system = "manual"
build_commands = [
	"autoreconf -fiv",
	"LINKS=\"/usr/bin/links\" ./configure --prefix=/usr",
	"sed -i 's/FORMAT_DIR=.*xmlto.*/\\t@true/' Makefile",
	"sed -i 's/FORMAT_DIR=.*xmlif.*/\\t@true/' Makefile",
	"make -j$RAD_CORES",
	"mkdir -p man/man1 && touch man/man1/xmlto.1 man/man1/xmlif.1"
]
install_command = "make DESTDIR=$DESTDIR install"
depends = "docbook-xml,docbook-xsl-nons,libxslt,links"
