[package]
name = "x264"
version = "20250815"
description = "x264 package provides a library for encoding video streams into the H.264/MPEG-4 AVC format"
source = "https://anduin.linuxfromscratch.org/BLFS/x264/x264-20250815.tar.xz"

[build]
system = "autotools"
configure_args = [
	"--enable-shared",
	"--disable-cli"
]
depends = "nasm"
