[package]
name = "nvidia-drivers"
version = "610.43.03"
description = "Nvidia proprietary drivers package"
source = "https://github.com/NVIDIA/open-gpu-kernel-modules/archive/refs/tags/610.43.03.tar.gz"

[build]
system = "manual"
build_commands = [
	"wget https://us.download.nvidia.com/XFree86/Linux-x86_64/610.43.03/NVIDIA-Linux-x86_64-610.43.03.run",
	"chmod +x NVIDIA-Linux-x86_64-610.43.03.run",
	"./NVIDIA-Linux-x86_64-610.43.03.run --extract-only",
	"make -C NVIDIA-Linux-x86_64-610.43.03/kernel modules -j$RAD_MAKEOPTS"
]
install_command = [
	"make -C NVIDIA-Linux-x86_64-610.43.03/kernel modules_install SYSSRC=/usr/src/linux-7.1.6 INSTALL_MOD_PATH=$DESTDIR",
	"mkdir -p $DESTDIR/usr/lib $DESTDIR/usr/bin $DESTDIR/usr/share/glvnd/egl_vendor.d $DESTDIR/usr/share/glvnd/egl_vendor.d $DESTDIR/usr/share/man/man1 $DESTDIR/usr/share/applications $DESTDIR/usr/share/pixmaps",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/*.so* $DESTDIR/usr/lib/",
	"find NVIDIA-Linux-x86_64-610.43.03 -maxdepth 1 -type f -executable -exec cp -a {} $DESTDIR/usr/bin/ \\;",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/*.1.gz $DESTDIR/usr/share/man/man1/ || true",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/10_nvidia.json $DESTDIR/usr/share/glvnd/egl_vendor.d/ || true",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/10_nvidia.json $DESTDIR/usr/share/glvnd/egl_vendor.d/ || true",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/nvidia-settings.desktop $DESTDIR/usr/share/applications/ || true",
	"cp -a NVIDIA-Linux-x86_64-610.43.03/nvidia-settings.png $DESTDIR/usr/share/pixmaps/ || true"
]
depends = "linux"
