[package]
name = "helium-bin"
version = "0.14.9.1"
description = "Privacy-first browser without distractions based on chromium"
source = "https://github.com/imputnet/helium-linux/releases/download/0.14.9.1/helium-0.14.9.1-x86_64_linux.tar.xz"

[build]
system = "manual"
build_commands = [
	"sed 's/helium/&-bin/' helium.desktop -i",
	"rm chrome",
	"mv helium helium-bin"
]
install_command = [
	"mkdir -p $DESTDIR/usr/lib/helium-bin $DESTDIR/usr/bin $DESTDIR/usr/share/applications $DESTDIR/usr/share/icons/hicolor/256x256/apps",
	"cp helium.desktop $DESTDIR/usr/share/applications/",
	"cp -r * $DESTDIR/usr/lib/helium-bin/",
	"cp product_logo_256.png $DESTDIR/usr/share/icons/hicolor/256x256/apps/helium-bin.png",
	"ln -s /usr/lib/helium-bin/helium-bin $DESTDIR/usr/bin/"
]
depends = "nspr,nss"
