[package]
name = "dwarves"
version = "1.30"
description = "The more-than-seven dwarves is a collection of tools that allows to inspect and query the DWARF information present in ELF files built with full debug information"
source = "https://github.com/acmel/dwarves/archive/refs/tags/v1.30.tar.gz"

[build]
system = "manual"
build_commands = [
	"mkdir build",
	"cmake -B build -S . -DCMAKE_INSTALL_PREFIX=/usr -D__LIBBPF_FIND_BY_PKGCONFIG=ON"
]
install_command = "make DESTDIR=$DESTDIR install"
depends = "elfutils"
