[package]
name = "spirv-tools"
version = "1.4.357.0"
description = "The SPIRV-Tools package contains libraries and utilities for processing SPIR-V modules"
source = "https://github.com/KhronosGroup/SPIRV-Tools/archive/vulkan-sdk-1.4.357.0/SPIRV-Tools-vulkan-sdk-1.4.357.0.tar.gz"

[build]
system = "cmake"
configure_args = [
	"-D SPIRV_WERROR=OFF",
	"-D BUILD_SHARED_LIBS=ON",
	"-D SPIRV_TOOLS_BUILD_STATIC=OFF",
	"-D SPIRV-Headers_SOURCE_DIR=/usr"
]
depends = "cmake,spirv-headers"
