[package]
name = "sassc"
version = "3.6.2"
description = "SassC is a wrapper around libsass, a CSS pre-processor language"
source = "https://github.com/sass/sassc/archive/3.6.2/sassc-3.6.2.tar.gz"

[build]
system = "manual"
build_commands = "autoreconf -fi && ./configure --prefix=/usr && make -j$RAD_MAKEOPTS"
install_command = "make install"
depends = "libsass"
